# Gems
exclude:
- README.md
- Gemfile
- Gemfile.lock
- coda-jekyll-theme.gemspec
- .jekyll-cache

plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num/"
base_url: "http://localhost:4000/"